version: '3.8'
services:
  gateway:
    build: .
    image: terrarium:dev
    container_name: terrarium-gateway
    environment:
     - AWS_ACCESS_KEY_ID
     - AWS_SECRET_ACCESS_KEY
     - AWS_DEFAULT_REGION
     - OTEL_EXPORTER_OTLP_ENDPOINT
    ports:
      - 50001:3001
    networks:
      - terrarium
    command:
      - gateway
      - "--aws-access-key-id"
      - "$AWS_ACCESS_KEY_ID"
      - "--aws-secret-access-key"
      - "$AWS_SECRET_ACCESS_KEY"
      - "--aws-region"
      - "$AWS_DEFAULT_REGION"
  registrar:
    build: .
    image: terrarium:dev
    container_name: terrarium-registrar-service
    environment:
     - AWS_ACCESS_KEY_ID
     - AWS_SECRET_ACCESS_KEY
     - AWS_DEFAULT_REGION
     - OTEL_EXPORTER_OTLP_ENDPOINT
    ports:
      - 50002:3001
    networks:
      - terrarium
    command:
      - registrar
      - "--aws-access-key-id"
      - "$AWS_ACCESS_KEY_ID"
      - "--aws-secret-access-key"
      - "$AWS_SECRET_ACCESS_KEY"
      - "--aws-region"
      - "$AWS_DEFAULT_REGION"
  browse:
    build: .
    image: terrarium:dev
    container_name: terrarium-browse-service
    environment:
     - AWS_ACCESS_KEY_ID
     - AWS_SECRET_ACCESS_KEY
     - AWS_DEFAULT_REGION
     - OTEL_EXPORTER_OTLP_ENDPOINT
    ports:
      - 50006:3001
    networks:
      - terrarium
    command:
      - browse
      - "--aws-access-key-id"
      - "$AWS_ACCESS_KEY_ID"
      - "--aws-secret-access-key"
      - "$AWS_SECRET_ACCESS_KEY"
      - "--aws-region"
      - "$AWS_DEFAULT_REGION"
      - "--registrar"
      - "terrarium-registrar-service:3001"
  tag-manager:
    build: .
    image: terrarium:dev
    container_name: terrarium-tag-manager-service
    environment:
     - AWS_ACCESS_KEY_ID
     - AWS_SECRET_ACCESS_KEY
     - AWS_DEFAULT_REGION
     - OTEL_EXPORTER_OTLP_ENDPOINT
    ports:
      - 50008:3001
    networks:
      - terrarium
    command:
      - tag-manager
      - "--aws-access-key-id"
      - "$AWS_ACCESS_KEY_ID"
      - "--aws-secret-access-key"
      - "$AWS_SECRET_ACCESS_KEY"
      - "--aws-region"
      - "$AWS_DEFAULT_REGION"
  version_manager:
    build: .
    image: terrarium:dev
    container_name: terrarium-version-service
    environment:
     - AWS_ACCESS_KEY_ID
     - AWS_SECRET_ACCESS_KEY
     - AWS_DEFAULT_REGION
     - OTEL_EXPORTER_OTLP_ENDPOINT
    ports:
      - 50003:3001
    networks:
      - terrarium
    command:
      - version-manager
      - "--aws-access-key-id"
      - "$AWS_ACCESS_KEY_ID"
      - "--aws-secret-access-key"
      - "$AWS_SECRET_ACCESS_KEY"
      - "--aws-region"
      - "$AWS_DEFAULT_REGION"
  dependency_manager:
    build: .
    image: terrarium:dev
    container_name: terrarium-dependency-service
    environment:
     - AWS_ACCESS_KEY_ID
     - AWS_SECRET_ACCESS_KEY
     - AWS_DEFAULT_REGION
     - OTEL_EXPORTER_OTLP_ENDPOINT
    ports:
      - 50004:3001
    networks:
      - terrarium
    command:
      - dependency-manager
      - "--aws-access-key-id"
      - "$AWS_ACCESS_KEY_ID"
      - "--aws-secret-access-key"
      - "$AWS_SECRET_ACCESS_KEY"
      - "--aws-region"
      - "$AWS_DEFAULT_REGION"
  storage:
    build: .
    image: terrarium:dev
    container_name: terrarium-storage-service
    environment:
     - AWS_ACCESS_KEY_ID
     - AWS_SECRET_ACCESS_KEY
     - AWS_DEFAULT_REGION
     - OTEL_EXPORTER_OTLP_ENDPOINT
    ports:
      - 50005:3001
    networks:
      - terrarium
    command:
      - storage
      - "--aws-access-key-id"
      - "$AWS_ACCESS_KEY_ID"
      - "--aws-secret-access-key"
      - "$AWS_SECRET_ACCESS_KEY"
      - "--aws-region"
      - "$AWS_DEFAULT_REGION"
networks:
  terrarium:
    name: terrarium
