version: '3.8'
services:
  gateway:
    build: .
    image: terrarium:dev
    container_name: terrarium-gateway
    environment:
     - AWS_ACCESS_KEY
     - AWS_SECRET_KEY
     - AWS_DEFAULT_REGION
    ports:
      - 50001:3001
    networks:
      - terrarium
    command:
      - gateway
      - "--aws-access-key"
      - "$AWS_ACCESS_KEY"
      - "--aws-secret-key"
      - "$AWS_SECRET_KEY"
      - "--aws-region"
      - "$AWS_DEFAULT_REGION"
    depends_on:
      - registrar
      - version
      - dependency
      - storage
  registrar_service:
    build: .
    image: terrarium:dev
    container_name: terrarium-registrar-service
    environment:
     - AWS_ACCESS_KEY
     - AWS_SECRET_KEY
     - AWS_DEFAULT_REGION
    ports:
      - 50002:3001
    networks:
      - terrarium
    command:
      - creation-service
      - "--aws-access-key"
      - "$AWS_ACCESS_KEY"
      - "--aws-secret-key"
      - "$AWS_SECRET_KEY"
      - "--aws-region"
      - "$AWS_DEFAULT_REGION"
  version_service:
    build: .
    image: terrarium:dev
    container_name: terrarium-version-service
    environment:
     - AWS_ACCESS_KEY
     - AWS_SECRET_KEY
     - AWS_DEFAULT_REGION
    ports:
      - 50003:3001
    networks:
      - terrarium
    command:
      - version-service
      - "--aws-access-key"
      - "$AWS_ACCESS_KEY"
      - "--aws-secret-key"
      - "$AWS_SECRET_KEY"
      - "--aws-region"
      - "$AWS_DEFAULT_REGION"
  dependency_service:
    build: .
    image: terrarium:dev
    container_name: terrarium-dependency-service
    environment:
     - AWS_ACCESS_KEY
     - AWS_SECRET_KEY
     - AWS_DEFAULT_REGION
    ports:
      - 50004:3001
    networks:
      - terrarium
    command:
      - dependency-service
      - "--aws-access-key"
      - "$AWS_ACCESS_KEY"
      - "--aws-secret-key"
      - "$AWS_SECRET_KEY"
      - "--aws-region"
      - "$AWS_DEFAULT_REGION"
  storage_service:
    build: .
    image: terrarium:dev
    container_name: terrarium-storage-service
    environment:
     - AWS_ACCESS_KEY
     - AWS_SECRET_KEY
     - AWS_DEFAULT_REGION
    ports:
      - 50005:3001
    networks:
      - terrarium
    command:
      - storage-service
      - "--aws-access-key"
      - "$AWS_ACCESS_KEY"
      - "--aws-secret-key"
      - "$AWS_SECRET_KEY"
      - "--aws-region"
      - "$AWS_DEFAULT_REGION"
networks:
  terrarium:
    name: terrarium
