version: '3.8'
services:
  gateway:
    build: .
    image: terrarium:dev
    container_name: terrarium-gateway
    environment:
     - AWS_ACCESS_KEY_ID
     - AWS_SECRET_ACCESS_KEY
     - AWS_DEFAULT_REGION
     - OTEL_EXPORTER_OTLP_ENDPOINT=http://jaeger:4317
    ports:
      - 50001:3001
    networks:
      - terrarium
    command:
      - gateway
      - "--aws-access-key-id"
      - "$AWS_ACCESS_KEY_ID"
      - "--aws-secret-access-key"
      - "$AWS_SECRET_ACCESS_KEY"
      - "--aws-region"
      - "$AWS_DEFAULT_REGION"
      - "--use-localstack"
      - "$USE_LOCALSTACK"
  registrar:
    build: .
    image: terrarium:dev
    container_name: terrarium-registrar-service
    environment:
     - AWS_ACCESS_KEY_ID
     - AWS_SECRET_ACCESS_KEY
     - AWS_DEFAULT_REGION
     - OTEL_EXPORTER_OTLP_ENDPOINT=http://jaeger:4317
    ports:
      - 50002:3001
    networks:
      - terrarium
    command:
      - registrar
      - "--aws-access-key-id"
      - "$AWS_ACCESS_KEY_ID"
      - "--aws-secret-access-key"
      - "$AWS_SECRET_ACCESS_KEY"
      - "--aws-region"
      - "$AWS_DEFAULT_REGION"
      - "--use-localstack"
      - "$USE_LOCALSTACK"
  browse:
    build: .
    image: terrarium:dev
    container_name: terrarium-browse-service
    environment:
     - AWS_ACCESS_KEY_ID
     - AWS_SECRET_ACCESS_KEY
     - AWS_DEFAULT_REGION
     - OTEL_EXPORTER_OTLP_ENDPOINT=http://jaeger:4317
    ports:
      - 50006:3001
    networks:
      - terrarium
    command:
      - browse
      - "--aws-access-key-id"
      - "$AWS_ACCESS_KEY_ID"
      - "--aws-secret-access-key"
      - "$AWS_SECRET_ACCESS_KEY"
      - "--aws-region"
      - "$AWS_DEFAULT_REGION"
      - "--registrar"
      - "terrarium-registrar-service:3001"
      - "--use-localstack"
      - "$USE_LOCALSTACK"
  tag-manager:
    build: .
    image: terrarium:dev
    container_name: terrarium-tag-manager-service
    environment:
     - AWS_ACCESS_KEY_ID
     - AWS_SECRET_ACCESS_KEY
     - AWS_DEFAULT_REGION
     - OTEL_EXPORTER_OTLP_ENDPOINT=http://jaeger:4317
    ports:
      - 50008:3001
    networks:
      - terrarium
    command:
      - tag-manager
      - "--aws-access-key-id"
      - "$AWS_ACCESS_KEY_ID"
      - "--aws-secret-access-key"
      - "$AWS_SECRET_ACCESS_KEY"
      - "--aws-region"
      - "$AWS_DEFAULT_REGION"
      - "--use-localstack"
      - "$USE_LOCALSTACK"
  version_manager:
    build: .
    image: terrarium:dev
    container_name: terrarium-version-service
    environment:
     - AWS_ACCESS_KEY_ID
     - AWS_SECRET_ACCESS_KEY
     - AWS_DEFAULT_REGION
     - OTEL_EXPORTER_OTLP_ENDPOINT=http://jaeger:4317
    ports:
      - 50003:3001
    networks:
      - terrarium
    command:
      - version-manager
      - "--aws-access-key-id"
      - "$AWS_ACCESS_KEY_ID"
      - "--aws-secret-access-key"
      - "$AWS_SECRET_ACCESS_KEY"
      - "--aws-region"
      - "$AWS_DEFAULT_REGION"
      - "--use-localstack"
      - "$USE_LOCALSTACK"
  provider_version_manager:
    build: .
    image: terrarium:dev
    container_name: provider-version-service
    environment:
     - AWS_ACCESS_KEY_ID
     - AWS_SECRET_ACCESS_KEY
     - AWS_DEFAULT_REGION
     - OTEL_EXPORTER_OTLP_ENDPOINT=http://jaeger:4317
    ports:
      - 50009:3001
    networks:
      - terrarium
    command:
      - provider-version-manager
      - "--aws-access-key-id"
      - "$AWS_ACCESS_KEY_ID"
      - "--aws-secret-access-key"
      - "$AWS_SECRET_ACCESS_KEY"
      - "--aws-region"
      - "$AWS_DEFAULT_REGION"
      - "--use-localstack"
      - "$USE_LOCALSTACK"
  dependency_manager:
    build: .
    image: terrarium:dev
    container_name: terrarium-dependency-service
    environment:
     - AWS_ACCESS_KEY_ID
     - AWS_SECRET_ACCESS_KEY
     - AWS_DEFAULT_REGION
     - OTEL_EXPORTER_OTLP_ENDPOINT=http://jaeger:4317
    ports:
      - 50004:3001
    networks:
      - terrarium
    command:
      - dependency-manager
      - "--aws-access-key-id"
      - "$AWS_ACCESS_KEY_ID"
      - "--aws-secret-access-key"
      - "$AWS_SECRET_ACCESS_KEY"
      - "--aws-region"
      - "$AWS_DEFAULT_REGION"
      - "--use-localstack"
      - "$USE_LOCALSTACK"
  storage:
    build: .
    image: terrarium:dev
    container_name: terrarium-storage-service
    environment:
     - AWS_ACCESS_KEY_ID
     - AWS_SECRET_ACCESS_KEY
     - AWS_DEFAULT_REGION
     - OTEL_EXPORTER_OTLP_ENDPOINT=http://jaeger:4317
    ports:
      - 50005:3001
    networks:
      - terrarium
    command:
      - storage
      - "--aws-access-key-id"
      - "$AWS_ACCESS_KEY_ID"
      - "--aws-secret-access-key"
      - "$AWS_SECRET_ACCESS_KEY"
      - "--aws-region"
      - "$AWS_DEFAULT_REGION"
      - "--use-localstack"
      - "$USE_LOCALSTACK"
  provider-storage:
    build: .
    image: terrarium:dev
    container_name: terrarium-provider-storage-service
    environment:
     - AWS_ACCESS_KEY_ID
     - AWS_SECRET_ACCESS_KEY
     - AWS_DEFAULT_REGION
     - OTEL_EXPORTER_OTLP_ENDPOINT=http://jaeger:4317
    ports:
      - 50010:3001
    networks:
      - terrarium
    command:
      - provider-storage
      - "--aws-access-key-id"
      - "$AWS_ACCESS_KEY_ID"
      - "--aws-secret-access-key"
      - "$AWS_SECRET_ACCESS_KEY"
      - "--aws-region"
      - "$AWS_DEFAULT_REGION"
      - "--use-localstack"
      - "$USE_LOCALSTACK"
  release:
    build: .
    image: terrarium:dev
    container_name: terrarium-release
    environment:
    - AWS_ACCESS_KEY_ID
    - AWS_SECRET_ACCESS_KEY
    - AWS_DEFAULT_REGION
    - OTEL_EXPORTER_OTLP_ENDPOINT=http://jaeger:4317
    ports:
      - 50007:3001
    networks:
      - terrarium
    command:
      - publish
      - "--aws-access-key-id"
      - "$AWS_ACCESS_KEY_ID"
      - "--aws-secret-access-key"
      - "$AWS_SECRET_ACCESS_KEY"
      - "--aws-region"
      - "$AWS_DEFAULT_REGION"
      - "--use-localstack"
      - "$USE_LOCALSTACK"
  jaeger:
    image: jaegertracing/all-in-one:1
    container_name: jaeger
    ports:
      - 16686:16686
      - 4317:4317
      - 4318:4318
    networks:
      - terrarium

networks:
  terrarium:
    name: terrarium
