// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.19.4
// source: internal/services/module_storage.proto

package services

import (
	context "context"
	terrarium "github.com/terrariumcloud/terrarium-grpc-gateway/pkg/terrarium"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// StorageClient is the client API for Storage service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type StorageClient interface {
	UploadSourceZip(ctx context.Context, opts ...grpc.CallOption) (Storage_UploadSourceZipClient, error)
	DownloadSourceZip(ctx context.Context, in *terrarium.DownloadSourceZipRequest, opts ...grpc.CallOption) (Storage_DownloadSourceZipClient, error)
}

type storageClient struct {
	cc grpc.ClientConnInterface
}

func NewStorageClient(cc grpc.ClientConnInterface) StorageClient {
	return &storageClient{cc}
}

func (c *storageClient) UploadSourceZip(ctx context.Context, opts ...grpc.CallOption) (Storage_UploadSourceZipClient, error) {
	stream, err := c.cc.NewStream(ctx, &Storage_ServiceDesc.Streams[0], "/terrarium.services.module.Storage/UploadSourceZip", opts...)
	if err != nil {
		return nil, err
	}
	x := &storageUploadSourceZipClient{stream}
	return x, nil
}

type Storage_UploadSourceZipClient interface {
	Send(*terrarium.UploadSourceZipChunkRequest) error
	CloseAndRecv() (*terrarium.TransactionStatusResponse, error)
	grpc.ClientStream
}

type storageUploadSourceZipClient struct {
	grpc.ClientStream
}

func (x *storageUploadSourceZipClient) Send(m *terrarium.UploadSourceZipChunkRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *storageUploadSourceZipClient) CloseAndRecv() (*terrarium.TransactionStatusResponse, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(terrarium.TransactionStatusResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *storageClient) DownloadSourceZip(ctx context.Context, in *terrarium.DownloadSourceZipRequest, opts ...grpc.CallOption) (Storage_DownloadSourceZipClient, error) {
	stream, err := c.cc.NewStream(ctx, &Storage_ServiceDesc.Streams[1], "/terrarium.services.module.Storage/DownloadSourceZip", opts...)
	if err != nil {
		return nil, err
	}
	x := &storageDownloadSourceZipClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Storage_DownloadSourceZipClient interface {
	Recv() (*terrarium.SourceZipChunkResponse, error)
	grpc.ClientStream
}

type storageDownloadSourceZipClient struct {
	grpc.ClientStream
}

func (x *storageDownloadSourceZipClient) Recv() (*terrarium.SourceZipChunkResponse, error) {
	m := new(terrarium.SourceZipChunkResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// StorageServer is the server API for Storage service.
// All implementations must embed UnimplementedStorageServer
// for forward compatibility
type StorageServer interface {
	UploadSourceZip(Storage_UploadSourceZipServer) error
	DownloadSourceZip(*terrarium.DownloadSourceZipRequest, Storage_DownloadSourceZipServer) error
	mustEmbedUnimplementedStorageServer()
}

// UnimplementedStorageServer must be embedded to have forward compatible implementations.
type UnimplementedStorageServer struct {
}

func (UnimplementedStorageServer) UploadSourceZip(Storage_UploadSourceZipServer) error {
	return status.Errorf(codes.Unimplemented, "method UploadSourceZip not implemented")
}
func (UnimplementedStorageServer) DownloadSourceZip(*terrarium.DownloadSourceZipRequest, Storage_DownloadSourceZipServer) error {
	return status.Errorf(codes.Unimplemented, "method DownloadSourceZip not implemented")
}
func (UnimplementedStorageServer) mustEmbedUnimplementedStorageServer() {}

// UnsafeStorageServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StorageServer will
// result in compilation errors.
type UnsafeStorageServer interface {
	mustEmbedUnimplementedStorageServer()
}

func RegisterStorageServer(s grpc.ServiceRegistrar, srv StorageServer) {
	s.RegisterService(&Storage_ServiceDesc, srv)
}

func _Storage_UploadSourceZip_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(StorageServer).UploadSourceZip(&storageUploadSourceZipServer{stream})
}

type Storage_UploadSourceZipServer interface {
	SendAndClose(*terrarium.TransactionStatusResponse) error
	Recv() (*terrarium.UploadSourceZipChunkRequest, error)
	grpc.ServerStream
}

type storageUploadSourceZipServer struct {
	grpc.ServerStream
}

func (x *storageUploadSourceZipServer) SendAndClose(m *terrarium.TransactionStatusResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *storageUploadSourceZipServer) Recv() (*terrarium.UploadSourceZipChunkRequest, error) {
	m := new(terrarium.UploadSourceZipChunkRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _Storage_DownloadSourceZip_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(terrarium.DownloadSourceZipRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(StorageServer).DownloadSourceZip(m, &storageDownloadSourceZipServer{stream})
}

type Storage_DownloadSourceZipServer interface {
	Send(*terrarium.SourceZipChunkResponse) error
	grpc.ServerStream
}

type storageDownloadSourceZipServer struct {
	grpc.ServerStream
}

func (x *storageDownloadSourceZipServer) Send(m *terrarium.SourceZipChunkResponse) error {
	return x.ServerStream.SendMsg(m)
}

// Storage_ServiceDesc is the grpc.ServiceDesc for Storage service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Storage_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "terrarium.services.module.Storage",
	HandlerType: (*StorageServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "UploadSourceZip",
			Handler:       _Storage_UploadSourceZip_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "DownloadSourceZip",
			Handler:       _Storage_DownloadSourceZip_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "internal/services/module_storage.proto",
}
