// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.19.4
// source: internal/services/module_session_manager.proto

package services

import (
	context "context"
	terrarium "github.com/terrariumcloud/terrarium-grpc-gateway/pkg/terrarium"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// SessionManagerClient is the client API for SessionManager service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SessionManagerClient interface {
	BeginVersion(ctx context.Context, in *BeginVersionRequest, opts ...grpc.CallOption) (*terrarium.BeginVersionResponse, error)
	AbortVersion(ctx context.Context, in *TerminateVersionRequest, opts ...grpc.CallOption) (*terrarium.TransactionStatusResponse, error)
	PublishVersion(ctx context.Context, in *TerminateVersionRequest, opts ...grpc.CallOption) (*terrarium.TransactionStatusResponse, error)
}

type sessionManagerClient struct {
	cc grpc.ClientConnInterface
}

func NewSessionManagerClient(cc grpc.ClientConnInterface) SessionManagerClient {
	return &sessionManagerClient{cc}
}

func (c *sessionManagerClient) BeginVersion(ctx context.Context, in *BeginVersionRequest, opts ...grpc.CallOption) (*terrarium.BeginVersionResponse, error) {
	out := new(terrarium.BeginVersionResponse)
	err := c.cc.Invoke(ctx, "/terrarium.services.module.SessionManager/BeginVersion", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sessionManagerClient) AbortVersion(ctx context.Context, in *TerminateVersionRequest, opts ...grpc.CallOption) (*terrarium.TransactionStatusResponse, error) {
	out := new(terrarium.TransactionStatusResponse)
	err := c.cc.Invoke(ctx, "/terrarium.services.module.SessionManager/AbortVersion", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sessionManagerClient) PublishVersion(ctx context.Context, in *TerminateVersionRequest, opts ...grpc.CallOption) (*terrarium.TransactionStatusResponse, error) {
	out := new(terrarium.TransactionStatusResponse)
	err := c.cc.Invoke(ctx, "/terrarium.services.module.SessionManager/PublishVersion", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SessionManagerServer is the server API for SessionManager service.
// All implementations must embed UnimplementedSessionManagerServer
// for forward compatibility
type SessionManagerServer interface {
	BeginVersion(context.Context, *BeginVersionRequest) (*terrarium.BeginVersionResponse, error)
	AbortVersion(context.Context, *TerminateVersionRequest) (*terrarium.TransactionStatusResponse, error)
	PublishVersion(context.Context, *TerminateVersionRequest) (*terrarium.TransactionStatusResponse, error)
	mustEmbedUnimplementedSessionManagerServer()
}

// UnimplementedSessionManagerServer must be embedded to have forward compatible implementations.
type UnimplementedSessionManagerServer struct {
}

func (UnimplementedSessionManagerServer) BeginVersion(context.Context, *BeginVersionRequest) (*terrarium.BeginVersionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BeginVersion not implemented")
}
func (UnimplementedSessionManagerServer) AbortVersion(context.Context, *TerminateVersionRequest) (*terrarium.TransactionStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AbortVersion not implemented")
}
func (UnimplementedSessionManagerServer) PublishVersion(context.Context, *TerminateVersionRequest) (*terrarium.TransactionStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PublishVersion not implemented")
}
func (UnimplementedSessionManagerServer) mustEmbedUnimplementedSessionManagerServer() {}

// UnsafeSessionManagerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SessionManagerServer will
// result in compilation errors.
type UnsafeSessionManagerServer interface {
	mustEmbedUnimplementedSessionManagerServer()
}

func RegisterSessionManagerServer(s grpc.ServiceRegistrar, srv SessionManagerServer) {
	s.RegisterService(&SessionManager_ServiceDesc, srv)
}

func _SessionManager_BeginVersion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BeginVersionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionManagerServer).BeginVersion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/terrarium.services.module.SessionManager/BeginVersion",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionManagerServer).BeginVersion(ctx, req.(*BeginVersionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SessionManager_AbortVersion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TerminateVersionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionManagerServer).AbortVersion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/terrarium.services.module.SessionManager/AbortVersion",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionManagerServer).AbortVersion(ctx, req.(*TerminateVersionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SessionManager_PublishVersion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TerminateVersionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionManagerServer).PublishVersion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/terrarium.services.module.SessionManager/PublishVersion",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionManagerServer).PublishVersion(ctx, req.(*TerminateVersionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SessionManager_ServiceDesc is the grpc.ServiceDesc for SessionManager service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SessionManager_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "terrarium.services.module.SessionManager",
	HandlerType: (*SessionManagerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "BeginVersion",
			Handler:    _SessionManager_BeginVersion_Handler,
		},
		{
			MethodName: "AbortVersion",
			Handler:    _SessionManager_AbortVersion_Handler,
		},
		{
			MethodName: "PublishVersion",
			Handler:    _SessionManager_PublishVersion_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "internal/services/module_session_manager.proto",
}
